# Generated by Django 4.2.30 on 2026-05-16 08:53

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=100, scale=0.5, size=[5000, 5000], upload_to='product_images/%Y%m%d'),
        ),
    ]
